apiVersion: v2
name: agentic-e2e-tester
description: A Helm chart for Agentic E2E Tester - AI-powered end-to-end testing system
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - testing
  - ai
  - microservices
  - e2e
  - spring-boot
home: https://github.com/your-org/agentic-e2e-tester
sources:
  - https://github.com/your-org/agentic-e2e-tester
maintainers:
  - name: Your Team
    email: team@yourcompany.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: "22.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "23.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
annotations:
  category: Testing
  licenses: Apache-2.0