spring:
  application:
    name: agentic-e2e-tester
  
  # Spring AI Configuration for Docker Ollama
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://ollama:11434}
      chat:
        model: codellama:7b
        options:
          temperature: 0.1
          top-p: 0.9
          max-tokens: 2000
    vectorstore:
      pgvector:
        host: postgres
        port: 5432
        database: vectordb
        username: postgres
        password: postgres
        schema-name: ai
        table-name: vector_store
        dimensions: 1536

  # Kafka Configuration for Docker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: agentic-e2e-tester
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

  # Couchbase Configuration for Docker
  couchbase:
    connection-string: ${COUCHBASE_CONNECTION_STRING:couchbase://couchbase}
    username: ${COUCHBASE_USERNAME:Administrator}
    password: ${COUCHBASE_PASSWORD:password}
    bucket-name: test-data

  # Web Configuration
  webflux:
    base-path: /api/v1

# Management and Actuator for Docker
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application Configuration for Docker
agentic:
  # Test Environment Configuration
  test-environment:
    active-environment: docker
    environments:
      docker:
        name: docker
        description: Docker containerized environment
        data-isolation-enabled: true
        cleanup-after-test: true
        max-concurrent-tests: 10
        test-timeout: PT15M

  # Test Data Configuration
  test-data:
    enabled: true
    auto-cleanup: true
    cleanup-delay: PT5M
    max-data-size-per-test: 1000
    enable-snapshots: true
    max-snapshots: 10
    enable-validation: true
    validation-timeout: PT30S

  # Service Discovery Configuration for Docker
  service-discovery:
    auto-discovery-enabled: true
    health-check-interval: 30
    discovery-interval: 60
    health-check-timeout: 5
    actuator-health-path: /actuator/health
    discovery-mechanisms:
      - actuator
      - configuration
    predefined-services:
      - service-id: order-service
        service-name: Order Service
        base-url: http://order-service:8080
        version: "1.0.0"
        metadata:
          type: microservice
          domain: order-management
      - service-id: payment-service
        service-name: Payment Service
        base-url: http://payment-service:8080
        version: "1.0.0"
        metadata:
          type: microservice
          domain: payment-processing
      - service-id: inventory-service
        service-name: Inventory Service
        base-url: http://inventory-service:8080
        version: "1.0.0"
        metadata:
          type: microservice
          domain: inventory-management
  
  testing:
    execution:
      timeout: 300s
      retry-attempts: 3
      parallel-execution: true
    correlation:
      header-name: X-Correlation-ID
    memory:
      pattern-storage-enabled: true
      max-patterns: 1000
    monitoring:
      real-time-reporting: true
      metrics-collection: true
      dashboard-refresh-interval: 5s
      metrics-retention-hours: 24
      alert-retention-hours: 72
  
  # REST API Integration Configuration
  rest:
    connection-timeout: 10000
    read-timeout: 30000
    write-timeout: 30000
    max-connections: 100
    max-connections-per-route: 20
  
  # Authentication Configuration
  auth:
    default-username: ${AGENTIC_AUTH_USERNAME:#{null}}
    default-password: ${AGENTIC_AUTH_PASSWORD:#{null}}
    default-token: ${AGENTIC_AUTH_TOKEN:#{null}}
    default-api-key: ${AGENTIC_AUTH_API_KEY:#{null}}

  # CI/CD Integration Configuration
  cicd:
    auto-trigger-enabled: false
    webhook:
      enabled: false

# Logging Configuration for Docker
logging:
  level:
    com.agentic: INFO
    org.springframework.ai: WARN
    org.springframework.kafka: WARN
    com.couchbase: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/agentic-e2e-tester.log