apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-config
  namespace: agentic-e2e-tester
  labels:
    app.kubernetes.io/name: agentic-e2e-tester
    app.kubernetes.io/component: config
data:
  application.yml: |
    spring:
      profiles:
        active: kubernetes
      ai:
        ollama:
          base-url: http://ollama-service:11434
          chat:
            model: codellama:7b
            options:
              temperature: 0.1
              top-p: 0.9
              max-tokens: 2048
      datasource:
        url: jdbc:postgresql://postgres-service:5432/vectordb
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      kafka:
        bootstrap-servers: kafka-service:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          acks: all
          retries: 3
        consumer:
          group-id: agentic-e2e-tester
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          auto-offset-reset: earliest
      data:
        redis:
          host: redis-service
          port: 6379
          password: ${REDIS_PASSWORD}
          timeout: 2000ms
          lettuce:
            pool:
              max-active: 8
              max-idle: 8
              min-idle: 0
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: when-authorized
      metrics:
        export:
          prometheus:
            enabled: true
      server:
        port: 8081
    
    agentic:
      testing:
        execution:
          max-concurrent-tests: 10
          default-timeout: PT10M
          step-timeout: PT2M
        correlation:
          timeout: PT30S
          max-trace-depth: 20
        ai:
          model-timeout: PT30S
          max-retries: 3
        security:
          enabled: true
          audit-enabled: true
        couchbase:
          connection-string: couchbase://couchbase-service
          username: ${COUCHBASE_USERNAME}
          password: ${COUCHBASE_PASSWORD}
          bucket: agentic-tests
    
    logging:
      level:
        root: INFO
        com.agentic.e2etester: DEBUG
        org.springframework.ai: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file:
        name: /app/logs/agentic-e2e-tester.log
        max-size: 100MB
        max-history: 30

  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    scrape_configs:
      - job_name: 'agentic-e2e-tester'
        static_configs:
          - targets: ['agentic-tester-service:8081']
        metrics_path: /actuator/prometheus
        scrape_interval: 10s
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - agentic-e2e-tester
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

  alert_rules.yml: |
    groups:
      - name: agentic-e2e-tester
        rules:
          - alert: AgenticTesterDown
            expr: up{job="agentic-e2e-tester"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Agentic E2E Tester is down"
              description: "Agentic E2E Tester has been down for more than 1 minute."
          
          - alert: HighTestFailureRate
            expr: rate(agentic_tests_failed_total[5m]) / rate(agentic_tests_total[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High test failure rate"
              description: "Test failure rate is {{ $value | humanizePercentage }} over the last 5 minutes."
          
          - alert: LongRunningTest
            expr: agentic_test_duration_seconds > 600
            for: 0m
            labels:
              severity: warning
            annotations:
              summary: "Long running test detected"
              description: "Test {{ $labels.test_id }} has been running for more than 10 minutes."